version: '3.8'

services:
  postgres:
    image: postgres:15.10
    container_name: docker-postgres200
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./mwas.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5437:5432"
    networks:
      - app-network

  app:
    build:
      context: . # Specify the directory containing your Dockerfile
    container_name: docker-app200
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker-postgres200:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8081"  # Exposes your Spring Boot app on port 8080
    depends_on:
      - postgres  # Ensures that PostgreSQL is up before your app starts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
