server:
  address: 0.0.0.0
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/pos-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:new_password}
#     url: jdbc:postgresql://127.0.0.1:5437/postgres
#     username: postgres
#     password: root


  jpa:
    hibernate:
      ddl-auto: none  # Set to none or another value based on your needs
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.jdbc.core: DEBUG
